### ISSUE TITLE
Allow to pass *.yaml to process multiple files at once

### ISSUE THREAD

**Issue by denniswebb** [kopeio/kexpand#30]
We keep our deployment, service, and ingress in separate template files.  When we currently update these, we must run `kexpand -f _dev.var deployment.yaml | kubectl apply -f -` multiple times for each file.  Having the ability to pass in multiple files or simply `*.yaml` would be useful.

I'm more than happy to do the PR for this, more just dropping it here for comments.

**Comment by justinsb** [comment]
I think that would be a really great feature.

I've been doing the `find | xargs` approach, but built in support would be great.  I presume you would just output with `---` separators.

**Comment by denniswebb** [comment]
Yes.  I can look at doing this in the next week or so.
